# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        files: ^src/
    -   id: end-of-file-fixer
        files: ^src/
    -   id: check-yaml
        files: ^src/
    -   id: check-added-large-files
        files: ^src/

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        files: ^src/

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest test/
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
